### ISSUE TITLE
undefined function split (PHP7)

### ISSUE THREAD

**Issue by lickx** [ft-/phpGridServer#11]
With inventory operations I get the following error with PHP7 in my Apache error log.
The [PHP split manual page](http://php.net/manual/en/function.split.php) suggests alternatives to this deprecated function with the most likely candidate being preg_split().

```
[Mon Jul 24 11:40:58.617662 2017] [mpm_prefork:notice] [pid 5342] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Jul 24 11:40:58.617746 2017] [core:notice] [pid 5342] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jul 24 12:09:36.315289 2017] [:error] [pid 5478] [client 127.0.0.1:59636] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), '815a4a89-6490-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_GETMULTIPLEITEMS.php(66): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:09:39.045607 2017] [:error] [pid 5478] [client 127.0.0.1:59637] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), '5588ec71-c403-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_GETMULTIPLEITEMS.php(66): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:09:45.547917 2017] [:error] [pid 5478] [client 127.0.0.1:59643] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:09:45.554265 2017] [:error] [pid 5478] [client 127.0.0.1:59644] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:09:45.558634 2017] [:error] [pid 5478] [client 127.0.0.1:59645] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:09:45.562575 2017] [:error] [pid 5478] [client 127.0.0.1:59646] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:11:23.253690 2017] [:error] [pid 5478] [client 127.0.0.1:59677] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), '815a4a89-6490-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_GETMULTIPLEITEMS.php(66): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:02.802789 2017] [:error] [pid 5478] [client 127.0.0.1:59698] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), '43a57e23-e6b7-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_DELETEITEMS.php(48): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:02.807363 2017] [:error] [pid 5478] [client 127.0.0.1:59699] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), '61ded8fc-7b17-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_DELETEITEMS.php(48): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:02.811442 2017] [:error] [pid 5478] [client 127.0.0.1:59700] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), '2a814dae-4c4d-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_DELETEITEMS.php(48): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:02.819563 2017] [:error] [pid 5478] [client 127.0.0.1:59701] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem(Object(UUID), 'f2f562c5-cd4a-4...')\n#2 /var/www/phpGridServer/xinventory/rpc_DELETEITEMS.php(48): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:07.303868 2017] [:error] [pid 5478] [client 127.0.0.1:59702] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:07.307403 2017] [:error] [pid 5478] [client 127.0.0.1:59705] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:07.310968 2017] [:error] [pid 5478] [client 127.0.0.1:59706] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23
[Mon Jul 24 12:12:07.314671 2017] [:error] [pid 5478] [client 127.0.0.1:59707] PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php:23\nStack trace:\n#0 /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php(184): mysql_inventoryItemFromRow(Array)\n#1 /var/www/phpGridServer/lib/accesscontrol/wrappers/AccessControlWrapper.php(68): MySQLInventoryServiceConnector->getItem('0a77aeef-9a8a-4...', Object(UUID))\n#2 /var/www/phpGridServer/xinventory/rpc_GETITEM.php(38): AccessControlWrapper->__call('getItem', Array)\n#3 /var/www/phpGridServer/rest_xinventory.php(117): require_once('/var/www/phpGri...')\n#4 {main}\n  thrown in /var/www/phpGridServer/lib/connectors/db/mysql/InventoryService.php on line 23

```

**Comment by ft-** [comment]
the direct candidate is explode but nevertheless it is an overlooked split
