### ISSUE TITLE
PHP Fatal error:  Uncaught NiniParseErrorException: Unsupported key 'flags' (InventoryItem Nini) in /var/www/phpgridserver/tools/loadninifile.php:374

### ISSUE THREAD

**Issue by neil2ball** [ft-/phpGridServer#14]
Parsing xml /opt/opensim/bin/inventory/Libraries.xml
Loading extra file OpenSimLibrary/OpenSimLibraryFolders.xml => /opt/opensim/bin/inventory/OpenSimLibrary/OpenSimLibraryFolders.xml
Loading extra file OpenSimLibrary/OpenSimLibrary.xml => /opt/opensim/bin/inventory/OpenSimLibrary/OpenSimLibrary.xml
Loading extra file AnimationsLibrary/AnimationsLibraryFolders.xml => /opt/opensim/bin/inventory/AnimationsLibrary/AnimationsLibraryFolders.xml
Checking inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66
Checking parent inventory folder id 00000112-000f-0000-0000-000100bba000 for inventory folder f0908f10-b9bf-11dc-95ff-0800200c9a66 Animations Library
Found inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66
Loading extra file AnimationsLibrary/AnimationsLibraryItems.xml => /opt/opensim/bin/inventory/AnimationsLibrary/AnimationsLibraryItems.xml
Checking asset id 8ceccb12-5aee-3584-e4a5-66973a844296 for inventory item 95b4febe-0385-e1b7-e70d-71325d2beea9 place_marker
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 95b4febe-0385-e1b7-e70d-71325d2beea9 place_marker
Checking inventory item id 95b4febe-0385-e1b7-e70d-71325d2beea9
Found inventory item id 95b4febe-0385-e1b7-e70d-71325d2beea9
Checking asset id 01645eeb-8c51-60dc-58cc-b9512f05afc0 for inventory item 43534bdd-d00c-a9d1-874f-b83543352d54 tpose2
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 43534bdd-d00c-a9d1-874f-b83543352d54 tpose2
Checking inventory item id 43534bdd-d00c-a9d1-874f-b83543352d54
Found inventory item id 43534bdd-d00c-a9d1-874f-b83543352d54
Checking asset id 53339f20-1811-f774-0768-0989f5e57df2 for inventory item 6d108351-1e10-e4f2-fe37-8e59ea890835 bouncy_ball_left
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 6d108351-1e10-e4f2-fe37-8e59ea890835 bouncy_ball_left
Checking inventory item id 6d108351-1e10-e4f2-fe37-8e59ea890835
Found inventory item id 6d108351-1e10-e4f2-fe37-8e59ea890835
Checking asset id 9e06424c-0178-82eb-ff21-6c0e4e5a7e6d for inventory item 10f8fdbb-466d-df61-cfc6-cb75b43d141c tpose
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 10f8fdbb-466d-df61-cfc6-cb75b43d141c tpose
Checking inventory item id 10f8fdbb-466d-df61-cfc6-cb75b43d141c
Found inventory item id 10f8fdbb-466d-df61-cfc6-cb75b43d141c
Checking asset id ddc2400f-ecdb-b00e-aee7-442ff99d5fb7 for inventory item 94a2e1bf-e31f-1cb6-de62-37527283cdc6 handshake
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 94a2e1bf-e31f-1cb6-de62-37527283cdc6 handshake
Checking inventory item id 94a2e1bf-e31f-1cb6-de62-37527283cdc6
Found inventory item id 94a2e1bf-e31f-1cb6-de62-37527283cdc6
Checking asset id b22af34d-740a-286f-f20a-e0818d91735e for inventory item 914021af-b614-a940-6f3b-6c76a102eb4e give_and_handshake
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 914021af-b614-a940-6f3b-6c76a102eb4e give_and_handshake
Checking inventory item id 914021af-b614-a940-6f3b-6c76a102eb4e
Found inventory item id 914021af-b614-a940-6f3b-6c76a102eb4e
Checking asset id be7b9b16-5c88-2862-2d20-ec4b939d6a8e for inventory item 6f3642e6-de37-7ad2-8fa2-6e1310a76e84 bouncy_ball_walk
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 6f3642e6-de37-7ad2-8fa2-6e1310a76e84 bouncy_ball_walk
Checking inventory item id 6f3642e6-de37-7ad2-8fa2-6e1310a76e84
Found inventory item id 6f3642e6-de37-7ad2-8fa2-6e1310a76e84
Checking asset id 9f2e3814-fc16-0b90-eeb8-5cf8a37fa3bd for inventory item f2e62518-0285-80c0-3530-abc6fe15ccf6 bouncy_ball_run
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item f2e62518-0285-80c0-3530-abc6fe15ccf6 bouncy_ball_run
Checking inventory item id f2e62518-0285-80c0-3530-abc6fe15ccf6
Found inventory item id f2e62518-0285-80c0-3530-abc6fe15ccf6
Checking asset id a0e08d1b-1f4b-5bae-8942-25ea578c80f6 for inventory item 42e422aa-4620-14b5-c7c0-ead9ccfd2df5 windsurf_left
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 42e422aa-4620-14b5-c7c0-ead9ccfd2df5 windsurf_left
Checking inventory item id 42e422aa-4620-14b5-c7c0-ead9ccfd2df5
Found inventory item id 42e422aa-4620-14b5-c7c0-ead9ccfd2df5
Checking asset id 8293c1a1-b7c8-26d8-b1e7-0512509112a5 for inventory item 6a2746a9-957d-b587-adce-7025bde55926 bouncy_ball_super
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 6a2746a9-957d-b587-adce-7025bde55926 bouncy_ball_super
Checking inventory item id 6a2746a9-957d-b587-adce-7025bde55926
Found inventory item id 6a2746a9-957d-b587-adce-7025bde55926
Checking asset id 2e349029-118a-995e-a7bf-d4fa32c1e9aa for inventory item 854dd926-bbbf-d2f7-e9bf-6877bc5916e4 bouncy_ball_right
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item 854dd926-bbbf-d2f7-e9bf-6877bc5916e4 bouncy_ball_right
Checking inventory item id 854dd926-bbbf-d2f7-e9bf-6877bc5916e4
Found inventory item id 854dd926-bbbf-d2f7-e9bf-6877bc5916e4
Checking asset id 626d9b8f-124f-f571-fc84-002bf28b9395 for inventory item c8048a47-90a2-4d07-123f-d81e758d3054 autograph_right
Checking parent inventory folder id f0908f10-b9bf-11dc-95ff-0800200c9a66 for inventory item c8048a47-90a2-4d07-123f-d81e758d3054 autograph_right
Checking inventory item id c8048a47-90a2-4d07-123f-d81e758d3054
Found inventory item id c8048a47-90a2-4d07-123f-d81e758d3054
Loading extra file BodyPartsLibrary/BodyPartsLibraryFolders.xml => /opt/opensim/bin/inventory/BodyPartsLibrary/BodyPartsLibraryFolders.xml
Checking inventory folder id d499e5e0-b9bf-11dc-95ff-0800200c9a66
Checking parent inventory folder id 00000112-000f-0000-0000-000100bba000 for inventory folder d499e5e0-b9bf-11dc-95ff-0800200c9a66 BodyParts Library
Found inventory folder id d499e5e0-b9bf-11dc-95ff-0800200c9a66
Loading extra file BodyPartsLibrary/BodyPartsLibraryItems.xml => /opt/opensim/bin/inventory/BodyPartsLibrary/BodyPartsLibraryItems.xml
PHP Fatal error:  Uncaught NiniParseErrorException: Unsupported key 'flags' (InventoryItem Nini) in /var/www/phpgridserver/tools/loadninifile.php:374
Stack trace:
#0 /var/www/phpgridserver/tools/loadninifile.php(576): parseNiniSection_InventoryItem(Object(XmlStringReader), '/opt/opensim/bi...', 'utf-8')
#1 /var/www/phpgridserver/tools/loadninifile.php(626): parseNiniMain(Object(XmlStringReader), 'Nini', '/opt/opensim/bi...', 'utf-8', 'InventoryItem')
#2 /var/www/phpgridserver/tools/loadninifile.php(537): parseNini('/opt/opensim/bi...', 'InventoryItem')
#3 /var/www/phpgridserver/tools/loadninifile.php(588): parseNiniSection_Default(Object(XmlStringReader), '/opt/opensim/bi...', 'utf-8')
#4 /var/www/phpgridserver/tools/loadninifile.php(626): parseNiniMain(Object(XmlStringReader), 'Nini', '/opt/opensim/bi...', 'utf-8', 'Default')
#5 /var/www/phpgridserver/tools/loadninifile.php(639): parseNini('/opt/opensim/bi...')
#6 {main}
  thrown in /var/www/phpgridserver/tools/loadninifile.php on line 374

**Comment by neil2ball** [comment]
Debian 9 LAMP stack OpenSim 0.9.0.1 post-fixes
